In [34]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [26]:
df  = pd.read_csv('Reddit_Title.csv')
df.head()

title  label
0  My aunt and uncle scoring their first gig as p...      0
1  How do I stop stressing about work when I'm at...      1
2  Meeting a fellow suicidal student in middle sc...      1
3  My brain feels literally numb. Is this depress...      1
4  A mother's reaction after seeing her son has p...      0

In [81]:
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['title'])
 
# printing label
label

array([3527, 1604, 3433, ..., 2641, 2561, 3089])

In [88]:
# removing the column 'Purchased' from df
# as it is of no use now.
df.drop("title", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
df["title"] = label
 
# printing Dataframe
df

label  title
0         0   3527
1         1   1604
2         1   3433
3         1   3572
4         0    182
...     ...    ...
5551      1   4262
5552      0   3689
5553      1   2641
5554      0   2561
5555      1   3089

[5556 rows x 2 columns]

In [89]:
swap_list  = ["title","label"]
df = df.reindex(columns=swap_list)
df

title  label
0      3527      0
1      1604      1
2      3433      1
3      3572      1
4       182      0
...     ...    ...
5551   4262      1
5552   3689      0
5553   2641      1
5554   2561      0
5555   3089      1

[5556 rows x 2 columns]

In [92]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [110]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [101]:
print(X_train)

[[ 1.60477463]
 [ 1.16792621]
 [ 0.9170504 ]
 ...
 [-0.14199498]
 [ 0.41592286]
 [-0.34731374]]


In [102]:
print(X_test)

[[-0.94142759]
 [-0.79165099]
 [ 1.11113592]
 ...
 [ 0.46023177]
 [-0.60193396]
 [-1.20790513]]


In [107]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [108]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 1]
 ...
 [1 0]
 [1 1]
 [1 1]]


In [112]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[506 198]
 [183 502]]


0.7257019438444925

In [126]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 10, stop = X_set[:, 1].max() + 10, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

decision tree


In [114]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [116]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [1 0]
 [1 1]
 [1 1]]


In [117]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[497 207]
 [207 478]]


0.7019438444924406

# Random Forest Classification

In [118]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)